
authentication:
  auth:
    tokenSecret: myTokenSecret
    tokenExpirationMsec: 3600000 #1 hour
    refreshTokenExpirationMsec: 7776000000 #90 days
    accessTokenCookieName: accessToken
    refreshTokenCookieName: refreshToken