authentication:
  auth:
    tokenSecret: ${TOKEN_SECRET}
    tokenExpirationMsec: ${EXPIRATION_TOKEN}
    refreshTokenExpirationMsec: 7776000000 
    accessTokenCookieName: accessToken
    refreshTokenCookieName: refreshToken